name: "🐛 Bug 反馈 | Bug Report"
description: "提交详细的错误报告 | Submit a detailed bug report"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📢 提交须知 | Notes Before Submitting
        - **优先处理 / Priority:** 严格按照此表单填写、信息详尽的 Issue 将会被优先排查和修复。/ Issues completed with detailed information will be prioritized.
        - **忽略声明 / May Be Closed:** 只有一句话描述、缺乏复现步骤或版本信息的 Issue 可能会被直接关闭而不予回复。/ One-line reports without reproduction steps or version details may be closed directly.
        - 感谢你的配合，这能帮我们节省大量沟通成本，让项目迭代更快！/ Thanks for your cooperation. It helps us reduce communication cost and iterate faster.
  - type: textarea
    id: bug-description
    attributes:
      label: "错误描述 | Bug Description"
      description: "请清晰简洁地描述这个 Bug 是什么。| Describe the bug clearly and concisely."
      placeholder: "例如：在同步 Memos 时提示网络错误... | Example: A network error appears when syncing Memos..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "复现步骤 | Steps To Reproduce"
      description: "请告诉我们如何触发这个错误。| Tell us how to reproduce this issue."
      placeholder: |
        1. 打开应用... | Open the app...
        2. 点击... | Tap...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: "应用版本 | App Version"
      placeholder: "例如：v1.0.2 | Example: v1.0.2"
    validations:
      required: false
  - type: input
    id: android-version
    attributes:
      label: "安卓系统版本 | Android Version"
      placeholder: "例如：Android 14 / HyperOS | Example: Android 14 / HyperOS"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "截图/日志 (可选) | Screenshots/Logs (Optional)"
      description: "建议上传截图或崩溃日志。| Screenshots or crash logs are highly recommended."
